// <auto-generated />
namespace WebApplication1.Migrations.LibraryMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialLibraryMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialLibraryMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201808131831523_initial Library Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
